name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo With Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build The Docker Image
      run: docker compose build
