name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo With Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run Docker Compose
      uses: hoverkraft-tech/compose-action@d2bee4f07e8ca410d6b196d00f90c12e7d48c33a # v2.6.0
      with:
        compose-file: "./docker/docker-compose.yml"

    - name: Build The Docker Image
      run: docker compose build
